<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from casereminder/xml/schema/CRM/Casereminder/CaseReminderLogType.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:bceb77bcff91cf927fe933b6883c2812)
 */
use CRM_Casereminder_ExtensionUtil as E;

/**
 * Database access object for the CaseReminderLogType entity.
 */
class CRM_Casereminder_DAO_CaseReminderLogType extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_reminder_log_type';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CaseReminderLogType ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * When log entry created.
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $log_time;

  /**
   * FK to Reminder Type
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $case_reminder_type_id;

  /**
   * Standardized description of action logged
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $action;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_reminder_log_type';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Reminder Log Types') : E::ts('Case Reminder Log Type');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'case_reminder_type_id', 'civicrm_case_reminder_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CaseReminderLogType ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_log_type.id',
          'table_name' => 'civicrm_case_reminder_log_type',
          'entity' => 'CaseReminderLogType',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderLogType',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'log_time' => [
          'name' => 'log_time',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Log Time'),
          'description' => E::ts('When log entry created.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_log_type.log_time',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_case_reminder_log_type',
          'entity' => 'CaseReminderLogType',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderLogType',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'case_reminder_type_id' => [
          'name' => 'case_reminder_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Case Reminder Type ID'),
          'description' => E::ts('FK to Reminder Type'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_log_type.case_reminder_type_id',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_log_type',
          'entity' => 'CaseReminderLogType',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderLogType',
          'localizable' => 0,
          'FKClassName' => 'CRM_Casereminder_DAO_CaseReminderType',
          'add' => NULL,
        ],
        'action' => [
          'name' => 'action',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Action'),
          'description' => E::ts('Standardized description of action logged'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_log_type.action',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_log_type',
          'entity' => 'CaseReminderLogType',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderLogType',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_reminder_log_type', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_reminder_log_type', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'action' => [
        'name' => 'action',
        'field' => [
          0 => 'action',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_case_reminder_log_type::0::action',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
