<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from casereminder/xml/schema/CRM/Casereminder/CaseReminderJob.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:01d1d6baf0f0ee7a13bee5edf36ef471)
 */
use CRM_Casereminder_ExtensionUtil as E;

/**
 * Database access object for the CaseReminderJob entity.
 */
class CRM_Casereminder_DAO_CaseReminderJob extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_reminder_job';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Paths for accessing this entity in the UI.
   *
   * @var string[]
   */
  protected static $_paths = [
    'view' => '/civicrm/admin/casereminder/jobrecipients#/?job=[id]',
  ];

  /**
   * Unique CaseReminderLogJob ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to reminderType
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $reminder_type_id;

  /**
   * When queue processing began for this job.
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $start;

  /**
   * When queue processing was completed for this job.
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $end;

  /**
   * When log entry created.
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_reminder_job';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Reminder Jobs') : E::ts('Case Reminder Job');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CaseReminderLogJob ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job.id',
          'table_name' => 'civicrm_case_reminder_job',
          'entity' => 'CaseReminderJob',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'reminder_type_id' => [
          'name' => 'reminder_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Reminder Type ID'),
          'description' => E::ts('FK to reminderType'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job.reminder_type_id',
          'table_name' => 'civicrm_case_reminder_job',
          'entity' => 'CaseReminderJob',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'localizable' => 0,
          'FKClassName' => 'CRM_Casereminder_DAO_CaseReminderType',
          'add' => NULL,
        ],
        'start' => [
          'name' => 'start',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Start'),
          'description' => E::ts('When queue processing began for this job.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job.start',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job',
          'entity' => 'CaseReminderJob',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'end' => [
          'name' => 'end',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('End'),
          'description' => E::ts('When queue processing was completed for this job.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job.end',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job',
          'entity' => 'CaseReminderJob',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'created' => [
          'name' => 'created',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created'),
          'description' => E::ts('When log entry created.'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job.created',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_case_reminder_job',
          'entity' => 'CaseReminderJob',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_reminder_job', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_reminder_job', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
