<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from casereminder/xml/schema/CRM/Casereminder/CaseReminderJobRecipientError.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d3422bb1be4c82a559b2ae3ab086be39)
 */
use CRM_Casereminder_ExtensionUtil as E;

/**
 * Database access object for the CaseReminderJobRecipientError entity.
 */
class CRM_Casereminder_DAO_CaseReminderJobRecipientError extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_reminder_job_recipient_error';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique CaseReminderJobRecipientError ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to casereminder job recipient
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $job_recipient_id;

  /**
   * When log entry created.
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created;

  /**
   * Error message
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $error_message;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_reminder_job_recipient_error';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Reminder Job Recipient Errors') : E::ts('Case Reminder Job Recipient Error');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CaseReminderJobRecipientError ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient_error.id',
          'table_name' => 'civicrm_case_reminder_job_recipient_error',
          'entity' => 'CaseReminderJobRecipientError',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipientError',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'job_recipient_id' => [
          'name' => 'job_recipient_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Job Recipient ID'),
          'description' => E::ts('FK to casereminder job recipient'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient_error.job_recipient_id',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient_error',
          'entity' => 'CaseReminderJobRecipientError',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipientError',
          'localizable' => 0,
          'FKClassName' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'add' => NULL,
        ],
        'created' => [
          'name' => 'created',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created'),
          'description' => E::ts('When log entry created.'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient_error.created',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_case_reminder_job_recipient_error',
          'entity' => 'CaseReminderJobRecipientError',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipientError',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'error_message' => [
          'name' => 'error_message',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Error Message'),
          'description' => E::ts('Error message'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient_error.error_message',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient_error',
          'entity' => 'CaseReminderJobRecipientError',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipientError',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_reminder_job_recipient_error', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_reminder_job_recipient_error', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
