<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from casereminder/xml/schema/CRM/Casereminder/CaseReminderJobRecipient.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:f3ec8a1a0a6ea774d46dfd19e2cc368c)
 */
use CRM_Casereminder_ExtensionUtil as E;

/**
 * Database access object for the CaseReminderJobRecipient entity.
 */
class CRM_Casereminder_DAO_CaseReminderJobRecipient extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_case_reminder_job_recipient';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Paths for accessing this entity in the UI.
   *
   * @var string[]
   */
  protected static $_paths = [
    'view' => '/civicrm/admin/casereminder/jobrecipientErrors#/?recipientId=[id]',
  ];

  /**
   * Unique CaseReminderLogRecipient ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to casereminder job
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $job_id;

  /**
   * FK to Case
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $case_id;

  /**
   * FK to Contact
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Is this recipient the case client?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_case_client;

  /**
   * Case Role relationship type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $relationship_type_id;

  /**
   * Email address to which reminder was sent (if any)
   *
   * @var string
   *   (SQL type: varchar(254))
   *   Note that values will be retrieved from the database as a string.
   */
  public $sent_to;

  /**
   * Standardized description of recipient status
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $status;

  /**
   * When was status updated?
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $status_time;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_case_reminder_job_recipient';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Case Reminder Job Recipients') : E::ts('Case Reminder Job Recipient');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique CaseReminderLogRecipient ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.id',
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'job_id' => [
          'name' => 'job_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Job ID'),
          'description' => E::ts('FK to casereminder job'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.job_id',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'FKClassName' => 'CRM_Casereminder_DAO_CaseReminderJob',
          'add' => NULL,
        ],
        'case_id' => [
          'name' => 'case_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Case ID'),
          'description' => E::ts('FK to Case'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.case_id',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'FKClassName' => 'CRM_Case_DAO_Case',
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.contact_id',
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'is_case_client' => [
          'name' => 'is_case_client',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Case Client'),
          'description' => E::ts('Is this recipient the case client?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.is_case_client',
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'add' => NULL,
        ],
        'relationship_type_id' => [
          'name' => 'relationship_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Case Role Relationship Type ID'),
          'description' => E::ts('Case Role relationship type'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.relationship_type_id',
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_RelationshipType',
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Relationship Type"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_relationship_type',
            'keyColumn' => 'id',
            'labelColumn' => 'label_a_b',
            'nameColumn' => 'name_a_b',
          ],
          'add' => '1.1',
        ],
        'sent_to' => [
          'name' => 'sent_to',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Sent To'),
          'description' => E::ts('Email address to which reminder was sent (if any)'),
          'required' => FALSE,
          'maxlength' => 254,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.sent_to',
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'description' => E::ts('Standardized description of recipient status'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.status',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'add' => NULL,
        ],
        'status_time' => [
          'name' => 'status_time',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Status Time'),
          'description' => E::ts('When was status updated?'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_case_reminder_job_recipient.status_time',
          'export' => TRUE,
          'table_name' => 'civicrm_case_reminder_job_recipient',
          'entity' => 'CaseReminderJobRecipient',
          'bao' => 'CRM_Casereminder_DAO_CaseReminderJobRecipient',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'case_reminder_job_recipient', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'case_reminder_job_recipient', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
