-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_case_reminder_log_type`;
DROP TABLE IF EXISTS `civicrm_case_reminder_log_case`;
DROP TABLE IF EXISTS `civicrm_case_reminder_job_recipient_error`;
DROP TABLE IF EXISTS `civicrm_case_reminder_job_recipient`;
DROP TABLE IF EXISTS `civicrm_case_reminder_job`;
DROP TABLE IF EXISTS `civicrm_case_reminder_type`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_case_reminder_type
-- *
-- * Case Reminder configurations per reminder type
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_type` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderType ID',
  `case_type_id` int unsigned COMMENT 'FK to Case Type',
  `case_status_id` varchar(256) COMMENT 'Case status ID(s), multi-value delimited. Implicit FK to civicrm_option_value where option_group = case_status.',
  `msg_template_id` int unsigned COMMENT 'FK to civicrm_msg_template',
  `recipient_relationship_type_id` varchar(256) COMMENT 'Relationship type ID(s) for recipients, multi-value delimited. Implicit FK to civicrm_relationship_type. -1 is Case Contact.',
  `from_email_address` varchar(256) COMMENT 'Email address selected from domain list of From addresses.',
  `subject` varchar(128) COMMENT 'Subject of reminder email',
  `dow` varchar(64) COMMENT 'Day of week to send reminders',
  `max_iterations` int unsigned COMMENT 'Maximum number of times to send a reminder of this type on any given case.',
  `is_active` tinyint COMMENT 'Is this reminder type active?',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_case_reminder_type_case_type_id FOREIGN KEY (`case_type_id`) REFERENCES `civicrm_case_type`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_case_reminder_type_msg_template_id FOREIGN KEY (`msg_template_id`) REFERENCES `civicrm_msg_template`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_case_reminder_job
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_job` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderLogJob ID',
  `reminder_type_id` int unsigned COMMENT 'FK to reminderType',
  `start` datetime NULL COMMENT 'When queue processing began for this job.',
  `end` datetime NULL COMMENT 'When queue processing was completed for this job.',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When log entry created.',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_case_reminder_job_reminder_type_id FOREIGN KEY (`reminder_type_id`) REFERENCES `civicrm_case_reminder_type`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_case_reminder_job_recipient
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_job_recipient` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderLogRecipient ID',
  `job_id` int unsigned NOT NULL COMMENT 'FK to casereminder job',
  `case_id` int unsigned NOT NULL COMMENT 'FK to Case',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact',
  `is_case_client` tinyint NOT NULL COMMENT 'Is this recipient the case client?',
  `relationship_type_id` int unsigned COMMENT 'Case Role relationship type',
  `sent_to` varchar(254) NULL COMMENT 'Email address to which reminder was sent (if any)',
  `status` varchar(255) COMMENT 'Standardized description of recipient status',
  `status_time` datetime NULL COMMENT 'When was status updated?',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_case_reminder_job_recipient_job_id FOREIGN KEY (`job_id`) REFERENCES `civicrm_case_reminder_job`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_case_reminder_job_recipient_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_case_reminder_job_recipient_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_case_reminder_job_recipient_relationship_type_id FOREIGN KEY (`relationship_type_id`) REFERENCES `civicrm_relationship_type`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_case_reminder_job_recipient_error
-- *
-- * Errors in queue processing for job recipients
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_job_recipient_error` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderJobRecipientError ID',
  `job_recipient_id` int unsigned NOT NULL COMMENT 'FK to casereminder job recipient',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When log entry created.',
  `error_message` varchar(255) NOT NULL COMMENT 'Error message',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_case_reminder_job_recipient_error_job_recipient_id FOREIGN KEY (`job_recipient_id`) REFERENCES `civicrm_case_reminder_job_recipient`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_case_reminder_log_case
-- *
-- * Logs for Case Reminders per case
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_log_case` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderLogCase ID',
  `log_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When log entry created.',
  `case_reminder_type_id` int unsigned NOT NULL COMMENT 'FK to Reminder Type',
  `case_id` int unsigned NOT NULL COMMENT 'FK to Case',
  `action` varchar(255) NOT NULL COMMENT 'Standardized description of action logged',
  PRIMARY KEY (`id`),
  INDEX `action`(action),
  CONSTRAINT FK_civicrm_case_reminder_log_case_case_reminder_type_id FOREIGN KEY (`case_reminder_type_id`) REFERENCES `civicrm_case_reminder_type`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_case_reminder_log_case_case_id FOREIGN KEY (`case_id`) REFERENCES `civicrm_case`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_case_reminder_log_type
-- *
-- * Logs for Case Reminder Types
-- *
-- *******************************************************/
CREATE TABLE `civicrm_case_reminder_log_type` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CaseReminderLogType ID',
  `log_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When log entry created.',
  `case_reminder_type_id` int unsigned NOT NULL COMMENT 'FK to Reminder Type',
  `action` varchar(255) NOT NULL COMMENT 'Standardized description of action logged',
  PRIMARY KEY (`id`),
  INDEX `action`(action),
  CONSTRAINT FK_civicrm_case_reminder_log_type_case_reminder_type_id FOREIGN KEY (`case_reminder_type_id`) REFERENCES `civicrm_case_reminder_type`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
